adobe/parliament-ui-components

- package-lock.json
- package.json
- src/Button/__stories__/button.stories.js
- src/Button/index.js
- src/index.js
@macdonst Do you want me to drop them one by one or all in one PR ? Ideally if the components exists, they should have the same API as the original ones else we can copy the API names from v2 wdyt?
> Add Button component

- src/ActionButton/__stories__/actionbutton.stories.js
- src/ActionButton/__stories__/actionbuttton.stories.js
- src/ActionButton/index.css
- src/ActionButton/index.js
- src/ActionButtons/__stories__/actionbuttons.stories.js
- src/ActionButtons/index.js
Updating the ActionButton and ActionButtons component to use rsv3 API's.
Deferring the big changes to ActionButtons until we get some clarity on how it will be specified.
> 🧱 Update ActionButton API

- src/Alert/__stories__/alert.stories.js
- src/Alert/index.js
Removes the header from Alert component and changes icon size.
#19 
Adhere to design
Updated our stories
> 💄 Issue #19: Design Feedback on Alert component

- src/Footer/index.js
Clean up footer component
n/a
Reduce duplication and make the code smaller.
Tested in storybook
> 🖼️  Update footer component

- package.json
- src/GlobalHeader/index.js
- src/GlobalHeader/stories/GlobalHeader.stories.js
- src/GlobalHeader/test/GlobalHeader.test.js
- src/Picker/index.js
- src/Popover/index.js
- src/Provider/index.js
- src/Tabs/index.js
- src/utils/index.js
- yarn.lock
@macdonst you mentioned you wanted to try out GlobalHeader so I started with this one. I'll do PRs one by one so once this is merged I'll move on with Code as it was also on the list.
> Add GlobalHeader

- src/GlobalHeader/stories/GlobalHeader.stories.js
Fixes the custom logo being shown in every story.
> Fix GlobalHeader storybook

- src/Search/index.js
Close search popup if you click outside the Search component.
n/a
Improves the user experience.
Tested in our Gatsby app
> 🎉  Close search popup if click outside component

- src/Code/index.js
- src/Nav/index.js
- src/Search/index.js
- src/TableOfContents/index.js
Fix some issues reported by axe
n/a
To provide a cleaner axe report
Run in storybook and gatsby develop
No visual changes
> ♿ Minor A11y fixes

- src/Grid/index.js
- src/OpenApiGrid/index.js
- src/index.js
Updates our Grid components to make room for the header
n/a
Updates our Grid components to make room for the header
Tested in parliament-client-template
> 🖼️  Grid with room for header

- src/Search/index.js
Turns off autocomplete for search
#50 
Gets rid of ugly browser generated suggestions
Gatsby develop and build
> 🐛  Issue #50: Turn off auto complete for Search

- .github/workflows/run-jest.yml
- src/AutoComplete/index.js
- src/Nav/index.js
- src/Nav/test/Nav.test.js
- src/RequestMaker/RequestMaker.js
- src/RequestMaker/stories/RequestMaker.stories.js
https://github.com/adobe/parliament-ui-components/commit/f5772112f855355d6f949b79612353fecce325c1 only partially implemented max depth. Consequently, https://github.com/adobe/parliament-client-template/pull/312 "broke" the Education template navs.
N/A
I fix da things. And then make robot yells at people.
See CI checks.
N/A
> Nav: Flesh out Implementation, Add Test & CI

- src/Heading/index.js
- src/Heading/stories/Heading.stories.js
- src/Heading/test/Heading.test.js
Changes the Headers so they don't hide all links. Just the last one, i.e. #
DEVEP-2749
To make the headers readable without having to hover over them.
Added new stories
Hover state for heading 2
> 🐛  DEVEP-2749: Markdown headers with links are invisible

- src/JsonSchema/docs/JsonSchema.md
- src/JsonSchema/index.js
- src/JsonSchema/stories/JsonSchema.stories.js
- src/JsonSchema/tests/JsonSchema.test.js
- src/index.js
Add a new component to be able to display JSON Schema's
DEVEP-2771
Allows us to display JSON Schema's as HTML pages.
Storybook and Jest tests
> Json schema

- src/JsonSchema/index.js
- src/JsonSchema/stories/JsonSchema.stories.js
Support schema's being passed in as strings
DEVEP-2784
When 
storybook
> 🐛  Support schema passed in as strings

- src/Code/index.js
- src/JsonSchema/stories/JsonSchema.stories.js
Enabled Code component to use JsonSchema to inline schemas
This way if you view the file on github it will use the json syntax highlighting but in parliament it will pick up the extra bit to say use the JsonSchema component.
- new story
- gatsby develop/build/serve
> 🎉  JsonSchema Code component

- package.json
- src/JsonSchema/index.js
- src/RequestMaker/RequestParameters.js
- src/RequestMaker/ResponsePanel.js
- src/RequestMaker/utils.js
- yarn.lock
Use tabs from monopackage instead of release candidate
n/a
To make sure our build doesn't break with the new version of react-spectrum.
- storybook
- unit tests
> Use Tabs in @adobe/react-spectrum 3.11.0

- .github/workflows/on-push-publish-to-npm.yml
- .github/workflows/run-jest.yml
- .github/workflows/version-bump-publish.yml
- package.json
> Use yarn instead of npm

- package.json
- src/Search/index.js
> Make Search default to results page on submit

- .github/workflows/on-push-publish-to-npm.yml
- .github/workflows/run-jest.yml
- .github/workflows/version-bump-publish.yml
- package.json
- yarn.lock
Version bump of redoc dependency.
Fixes many bugs documented in more recent versions of `redoc`: https://github.com/Redocly/redoc/releases
Ran tests described in documentation
> redoc version bump to 2.1.3

- .github/workflows/on-push-publish-to-npm.yml
- .github/workflows/run-jest.yml
- .github/workflows/version-bump-publish.yml
- package.json
- yarn.lock
Reverts adobe/parliament-ui-components#199
> Revert "redoc version bump to 2.1.3"
